### ISSUE TITLE
v 1.4.1 not converting audio on Windows 10?

### ISSUE THREAD

**Issue by sgenterlein** [asivery/webminidisc#26]
Hi there. I am so thankful for Web MD Pro and I've been using it for many months now without any issues (always SP using default encoder). However, since this afternoon, I can no longer convert any audio; it gets stuck at the first track, 0%. I tried reinstalling the drivers, used different files, different recorders, restarted everything, switched encoders, but no luck.
Chrome is Version 116.0.5845.180 (Official Build) (64-bit)
Computer is running Win 10 Pro 10.0.19045 Build 19045 if that matters. I installed an update today so maybe that broke something?

**Comment by sgenterlein** [comment]
UPDATE: It seems to work on my work laptop running Win 11 Business... Any suggestions what else I could try?

**Comment by sgenterlein** [comment]
UPDATE2: I tried it on another Lenovo laptop running Win 10 and no luck either. Maybe it is related to the last Windows update?

**Comment by asivery** [comment]
@sgenterlein I can confirm that it's an issue. Your other machine works, because it has cached a working copy of the webapp. I'll let you know once it's fixed.

**Comment by sgenterlein** [comment]
Much appreciated! For the time being, I moved things to my work laptop. Can't thank you enough for what you're doing for the MD community!

**Comment by asivery** [comment]
Thanks for the kind words :) It should now be fixed. Please empty the cache on the other computer, and see if it works now.

**Comment by sgenterlein** [comment]
Not sure if I'll get around to it tonight, but I'll do it tomorrow for sure!

**Comment by asivery** [comment]
Great! No need to hurry - just please let me know if the problem is gone now. I can no longer reproduce the issue, but I just want to make sure it's gone for good :)

**Comment by sgenterlein** [comment]
Hey, I cleared my cache but the problem still persists. Could you please tell me what exactly I need to remove/delete?

**Comment by sgenterlein** [comment]
Wait! it just decided to work. Maybe it took a minute to register. I'll let you know if anything changes!

**Comment by sgenterlein** [comment]
Issue resolved, thanks!
